// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           32
// Async Callback (empty):               1
// Total number of exported functions:  35

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    festival_smart_contract
    (
        init => init
        upgrade => upgrade
        addFestival => add_festival
        addEvent => add_event
        addTicketPrice => add_ticket_price
        addFlashEvent => add_flash_event
        setTicketTokenIdentifier => set_ticket_token_identifier
        addProduct => add_product
        setBonusPercentage => set_bonus_percentage
        setEgldToUsdRate => set_egld_to_usd_rate
        setResaleMaxMultiplier => set_resale_max_multiplier
        addFunds => add_funds
        buyProduct => buy_product
        buyTicket => buy_ticket
        createParticipant => create_participant
        checkIn => check_in
        checkOut => check_out
        claimFlashEventPoints => claim_flash_event_points
        putTicketForSale => put_ticket_for_sale
        buyResaleTicket => buy_resale_ticket
        getFestivalData => get_festival_data
        getTicketPrices => get_ticket_prices_view
        getProducts => get_products
        getBraceletFunds => get_bracelet_funds
        getAllFestivals => get_all_festivals
        getEventsForFestival => get_events_for_festival
        getBonusPercentage => get_bonus_percentage
        getEgldToUsdRate => get_egld_to_usd_rate
        getLeaderboard => get_leaderboard
        getTicketStatus => get_ticket_status
        getResaleMaxMultiplier => get_resale_max_multiplier
        getTicketOriginalPrice => get_ticket_original_price
        getResaleInfo => get_resale_info
        getResaleTicketsForFestival => get_resale_tickets_for_festival
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
