// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    festival_smart_contract
    (
        init => init
        upgrade => upgrade
        addFestival => add_festival
        addEvent => add_event
        addTicketPrice => add_ticket_price
        addFlashEvent => add_flash_event
        setTicketTokenIdentifier => set_ticket_token_identifier
        buyTicket => buy_ticket
        createParticipant => create_participant
        checkIn => check_in
        checkOut => check_out
        claimFlashEventPoints => claim_flash_event_points
        putTicketForSale => put_ticket_for_sale
        buyResaleTicket => buy_resale_ticket
        getFestivalData => get_festival_data
        getTicketPrices => get_ticket_prices_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
